import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { signIn, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const router = useRouter();
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <section className="dark:bg-gray-800 dark:text-gray-100">
          <div className="container mx-auto flex flex-col items-center px-4 py-16 text-center md:py-32 md:px-10 lg:px-32 xl:max-w-3xl">
            <h1 className="text-4xl font-bold leading-none sm:text-5xl">
              Welcome to Total Time Tracker
            </h1>
            <p className="mt-8 mb-12 px-8 text-lg">
              You can use this website to track your total time spent on an
              activity over the course of a day, week, month, or year.
            </p>
            <div className="flex flex-wrap justify-center">
              {session ? (
                <button
                  className="m-2 rounded px-8 py-3 text-lg font-semibold"
                  role="button"
                  onClick={() => {
                    void router.push("/dashboard");
                  }}
                >
                  Dashboard
                </button>
              ) : (
                <button
                  className="m-2 rounded px-8 py-3 text-lg font-semibold"
                  role="button"
                  onClick={() => {
                    void signIn("google");
                  }}
                >
                  Sign In
                </button>
              )}

              <button
                onClick={() => {
                  void router.push("/about");
                }}
                className="m-2 rounded border px-8 py-3 text-lg"
              >
                Learn more
              </button>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
